#! /bin/bash
echo "---------------------------------------------------------------------------------------------| "
echo "  |      01       111010011    0101        01        01      01        01      01            | "
echo "  |      01          01        01  01      01        01      01          01  01              | "
echo "  |      01          01        01    01    01        01      01            01                | "
echo "  |      01          01        01      01  01        01      01          01   01             | "
echo "  |      010101   010101010    01        0101        0101010101        01       01           | "
echo "---------------------------------------------------------------------------------------------| "

while :
do 


echo " Atraves de que Interface vas a configurar"

echo "[1] Interface Cableada"

echo "[2] Interface Inalambrica"

echo "[3] Salir del script"

echo "Ingresa la opción: "
read opcion

case $opcion in


1) echo "Interface Cableada:";

echo "[1] Configuracion Estática"
echo "[2] Configuracion Dinámica"

echo "Ingresa la opción: " 
read opcion

case $opcion in

1) echo "Configuracion Estática: "

echo -e "Interfaces de red disponibles"
sudo ifconfig
sleep 7

echo -e "Nombre de la interface"
read interfaz
echo -e "Dame la ip "
read ip
echo -e "Dame la mascara"
read mascara

sudo ifconfig $interfaz $ip netmask $mascara up
echo -e "se configuro bien "

echo -e "ingresa el gateway: "
read gw
route add default gw $gw

;;

2) echo "Configuracin Dinámica: "

echo -e "Interfaces de red "
sudo ifconfig
sleep 7

echo -e "Nombre de la interface a configurar"
read interfaz

sudo dhclient $interfaz

;;

esac
;;

2) echo "Interface Inalambrica: "

echo "[1] Configuracion Estática"
echo "[2] Configuracion Dinámica"

echo "Ingresa la opción: " 
read opcion

case $opcion in

1) echo "Configuracion Estática: "
echo -e "interfaces disponibles"
sudo ifconfig
sleep 7

echo -e "Inerface a configurar"
read interfaz
echo -e "se mostraran las redes disponibles"
sudo iwlist $interfaz scan
echo -e "Ingresa el ESSID de la red a la que deseas acceder: "
read essid
echo -e "Si la red tiene contraseña, ingresala: "
read pass

sudo iwconfig $interfaz essid $essid key s:$pass

echo -e "Dame la ip"
read ip
echo -e "Ingresa la mascara de red "
read mascara

sudo ifconfig $interfaz $ip netmask $mascara up
echo -e "SE HA CONFIGURADO CORRECTAMENTE"

echo -e "\nIngresa la ip del gateway: "
read gw
route add default gw $gw

;;

2) echo -e "Configuracion Dinámica: "
echo -e "\nSE MOSTRARAN LAS INTERFACES DE RED\n"
sudo ifconfig
sleep 7

echo -e "nombre de la interface a configurar"
read interfaz
echo -e "\n*Se mostraran las redes disponibles*"
sudo iwlist $interfaz scan
echo -e "\nIngresa el ESSID de la red a la que deseas acceder: "
read essid
echo -e "\nSi la red tiene contraseña, ingresala: "
read pass

sudo iwconfig $interfaz essid $essid key s:$pass

sudo dhclient $interfaz

;;

esac
;;

3) echo "saliendo del script ";

exit 1;;

esac
done

